name: Release Lammrelease

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: Jeremy27/LammCI/.github/workflows/app-release.yml@main
    with:
      app-name: Lammrelease
    permissions:
      contents: write
      packages: read
